version: '3.9'

services:
  db:
    build:
      context: ./db
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Un!q@to2023
      MSSQL_PID: Developer
    ports:
      - "1433:5433"
    networks:
      - app_network

  web:
    build:
      context: ./web-server
    ports:
      - "8000:80"
    networks:
      - app_network
    depends_on:
      - db
    

networks:
  app_network:
    #driver: bridge